export const product = {
    "AMZ": {
      "Phone": [
        { "productName": "Phone 1", "price": 699, "rating": 4.5, "discount": 10, "availability": "yes" },
        { "productName": "Phone 2", "price": 799, "rating": 4.6, "discount": 12, "availability": "yes" },
        { "productName": "Phone 3", "price": 899, "rating": 4.7, "discount": 15, "availability": "yes" },
        { "productName": "Phone 4", "price": 999, "rating": 4.8, "discount": 18, "availability": "yes" },
        { "productName": "Phone 5", "price": 1099, "rating": 4.9, "discount": 20, "availability": "yes" },
        { "productName": "Phone 6", "price": 649, "rating": 4.3, "discount": 8, "availability": "yes" },
        { "productName": "Phone 7", "price": 549, "rating": 4.1, "discount": 5, "availability": "yes" },
        { "productName": "Phone 8", "price": 749, "rating": 4.4, "discount": 11, "availability": "yes" },
        { "productName": "Phone 9", "price": 849, "rating": 4.5, "discount": 13, "availability": "yes" },
        { "productName": "Phone 10", "price": 949, "rating": 4.6, "discount": 16, "availability": "yes" },
        { "productName": "Phone 11", "price": 1049, "rating": 4.7, "discount": 18, "availability": "yes" },
        { "productName": "Phone 12", "price": 1149, "rating": 4.8, "discount": 20, "availability": "yes" },
        { "productName": "Phone 13", "price": 1199, "rating": 4.9, "discount": 25, "availability": "yes" },
        { "productName": "Phone 14", "price": 1249, "rating": 5.0, "discount": 30, "availability": "yes" },
        { "productName": "Phone 15", "price": 699, "rating": 4.2, "discount": 10, "availability": "yes" },
        { "productName": "Phone 16", "price": 799, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Phone 17", "price": 899, "rating": 4.4, "discount": 14, "availability": "yes" },
        { "productName": "Phone 18", "price": 999, "rating": 4.5, "discount": 16, "availability": "yes" },
        { "productName": "Phone 19", "price": 1099, "rating": 4.6, "discount": 18, "availability": "yes" },
        { "productName": "Phone 20", "price": 1199, "rating": 4.7, "discount": 20, "availability": "yes" }
      ],
      "Computer": [
        { "productName": "Computer 1", "price": 499, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Computer 2", "price": 599, "rating": 4.2, "discount": 8, "availability": "yes" },
        { "productName": "Computer 3", "price": 699, "rating": 4.3, "discount": 10, "availability": "yes" },
        { "productName": "Computer 4", "price": 799, "rating": 4.4, "discount": 12, "availability": "yes" },
        { "productName": "Computer 5", "price": 899, "rating": 4.5, "discount": 15, "availability": "yes" },
        { "productName": "Computer 6", "price": 999, "rating": 4.6, "discount": 18, "availability": "yes" },
        { "productName": "Computer 7", "price": 1099, "rating": 4.7, "discount": 20, "availability": "yes" },
        { "productName": "Computer 8", "price": 1199, "rating": 4.8, "discount": 22, "availability": "yes" },
        { "productName": "Computer 9", "price": 1299, "rating": 4.9, "discount": 25, "availability": "yes" },
        { "productName": "Computer 10", "price": 1399, "rating": 5.0, "discount": 30, "availability": "yes" },
        { "productName": "Computer 11", "price": 1499, "rating": 4.1, "discount": 35, "availability": "yes" },
        { "productName": "Computer 12", "price": 1599, "rating": 4.2, "discount": 40, "availability": "yes" },
        { "productName": "Computer 13", "price": 1699, "rating": 4.3, "discount": 45, "availability": "yes" },
        { "productName": "Computer 14", "price": 1799, "rating": 4.4, "discount": 50, "availability": "yes" },
        { "productName": "Computer 15", "price": 1899, "rating": 4.5, "discount": 55, "availability": "yes" },
        { "productName": "Computer 16", "price": 1999, "rating": 4.6, "discount": 60, "availability": "yes" },
        { "productName": "Computer 17", "price": 2099, "rating": 4.7, "discount": 65, "availability": "yes" },
        { "productName": "Computer 18", "price": 2199, "rating": 4.8, "discount": 70, "availability": "yes" },
        { "productName": "Computer 19", "price": 2299, "rating": 4.9, "discount": 75, "availability": "yes" },
        { "productName": "Computer 20", "price": 2399, "rating": 5.0, "discount": 80, "availability": "yes" }
      ],
      "TV": [
        { "productName": "TV 1", "price": 299, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "TV 2", "price": 399, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "TV 3", "price": 499, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "TV 4", "price": 599, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "TV 5", "price": 699, "rating": 4.4, "discount": 15, "availability": "yes" },
        { "productName": "TV 6", "price": 799, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "TV 7", "price": 899, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "TV 8", "price": 999, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "TV 9", "price": 1099, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "TV 10", "price": 1199, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "TV 11", "price": 1299, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "TV 12", "price": 1399, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "TV 13", "price": 1499, "rating": 4.1, "discount": 50, "availability": "yes" },
        { "productName": "TV 14", "price": 1599, "rating": 4.2, "discount": 55, "availability": "yes" },
        { "productName": "TV 15", "price": 1699, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "TV 16", "price": 1799, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "TV 17", "price": 1899, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "TV 18", "price": 1999, "rating": 4.6, "discount": 75, "availability": "yes" },
        { "productName": "TV 19", "price": 2099, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "TV 20", "price": 2199, "rating": 4.8, "discount": 85, "availability": "yes" }
      ],
      "Earphone": [
        { "productName": "Earphone 1", "price": 49, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Earphone 2", "price": 59, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "Earphone 3", "price": 69, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "Earphone 4", "price": 79, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Earphone 5", "price": 89, "rating": 4.4, "discount": 15, "availability": "yes" },
        { "productName": "Earphone 6", "price": 99, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "Earphone 7", "price": 109, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "Earphone 8", "price": 119, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "Earphone 9", "price": 129, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "Earphone 10", "price": 139, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "Earphone 11", "price": 149, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "Earphone 12", "price": 159, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "Earphone 13", "price": 169, "rating": 4.1, "discount": 50, "availability": "yes" },
        { "productName": "Earphone 14", "price": 179, "rating": 4.2, "discount": 55, "availability": "yes" },
        { "productName": "Earphone 15", "price": 189, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "Earphone 16", "price": 199, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "Earphone 17", "price": 209, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "Earphone 18", "price": 219, "rating": 4.6, "discount": 75, "availability": "yes" },
        { "productName": "Earphone 19", "price": 229, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "Earphone 20", "price": 239, "rating": 4.8, "discount": 85, "availability": "yes" }
      ],
      "Remote": [
        { "productName": "Remote 1", "price": 29, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Remote 2", "price": 39, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "Remote 3", "price": 49, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "Remote 4", "price": 59, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Remote 5", "price": 69, "rating": 4.4, "discount": 15, "availability": "yes" },
        { "productName": "Remote 6", "price": 79, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "Remote 7", "price": 89, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "Remote 8", "price": 99, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "Remote 9", "price": 109, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "Remote 10", "price": 119, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "Remote 11", "price": 129, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "Remote 12", "price": 139, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "Remote 13", "price": 149, "rating": 4.1, "discount": 50, "availability": "yes" },
        { "productName": "Remote 14", "price": 159, "rating": 4.2, "discount": 55, "availability": "yes" },
        { "productName": "Remote 15", "price": 169, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "Remote 16", "price": 179, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "Remote 17", "price": 189, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "Remote 18", "price": 199, "rating": 4.6, "discount": 75, "availability": "no" },
        { "productName": "Remote 19", "price": 209, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "Remote 20", "price": 219, "rating": 4.8, "discount": 85, "availability": "yes" }
      ],
      "Speaker": [
        { "productName": "Speaker 1", "price": 129, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Speaker 2", "price": 139, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "Speaker 3", "price": 149, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "Speaker 4", "price": 159, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Speaker 5", "price": 169, "rating": 4.4, "discount": 15, "availability": "no" },
        { "productName": "Speaker 6", "price": 179, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "Speaker 7", "price": 189, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "Speaker 8", "price": 199, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "Speaker 9", "price": 209, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "Speaker 10", "price": 219, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "Speaker 11", "price": 229, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "Speaker 12", "price": 239, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "Speaker 13", "price": 249, "rating": 4.1, "discount": 50, "availability": "no" },
        { "productName": "Speaker 14", "price": 259, "rating": 4.2, "discount": 55, "availability": "no" },
        { "productName": "Speaker 15", "price": 269, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "Speaker 16", "price": 279, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "Speaker 17", "price": 289, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "Speaker 18", "price": 299, "rating": 4.6, "discount": 75, "availability": "yes" },
        { "productName": "Speaker 19", "price": 309, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "Speaker 20", "price": 319, "rating": 4.8, "discount": 85, "availability": "yes" }
      ],
      "Headset": [
        { "productName": "Headset 1", "price": 99, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Headset 2", "price": 109, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "Headset 3", "price": 119, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "Headset 4", "price": 129, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Headset 5", "price": 139, "rating": 4.4, "discount": 15, "availability": "yes" },
        { "productName": "Headset 6", "price": 149, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "Headset 7", "price": 159, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "Headset 8", "price": 169, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "Headset 9", "price": 179, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "Headset 10", "price": 189, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "Headset 11", "price": 199, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "Headset 12", "price": 209, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "Headset 13", "price": 219, "rating": 4.1, "discount": 50, "availability": "yes" },
        { "productName": "Headset 14", "price": 229, "rating": 4.2, "discount": 55, "availability": "yes" },
        { "productName": "Headset 15", "price": 239, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "Headset 16", "price": 249, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "Headset 17", "price": 259, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "Headset 18", "price": 269, "rating": 4.6, "discount": 75, "availability": "yes" },
        { "productName": "Headset 19", "price": 279, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "Headset 20", "price": 289, "rating": 4.8, "discount": 85, "availability": "yes" }
      ],
      "Laptop": [
        { "productName": "Laptop 1", "price": 2236, "rating": 4.0, "discount": 5, "availability": "yes" },
        { "productName": "Laptop 2", "price": 2246, "rating": 4.1, "discount": 7, "availability": "yes" },
        { "productName": "Laptop 3", "price": 2256, "rating": 4.2, "discount": 9, "availability": "yes" },
        { "productName": "Laptop 4", "price": 2266, "rating": 4.3, "discount": 12, "availability": "yes" },
        { "productName": "Laptop 5", "price": 2276, "rating": 4.4, "discount": 15, "availability": "yes" },
        { "productName": "Laptop 6", "price": 2286, "rating": 4.5, "discount": 18, "availability": "yes" },
        { "productName": "Laptop 7", "price": 2296, "rating": 4.6, "discount": 20, "availability": "yes" },
        { "productName": "Laptop 8", "price": 2306, "rating": 4.7, "discount": 25, "availability": "yes" },
        { "productName": "Laptop 9", "price": 2316, "rating": 4.8, "discount": 30, "availability": "yes" },
        { "productName": "Laptop 10", "price": 2326, "rating": 4.9, "discount": 35, "availability": "yes" },
        { "productName": "Laptop 11", "price": 2336, "rating": 5.0, "discount": 40, "availability": "yes" },
        { "productName": "Laptop 12", "price": 2346, "rating": 4.0, "discount": 45, "availability": "yes" },
        { "productName": "Laptop 13", "price": 2356, "rating": 4.1, "discount": 50, "availability": "yes" },
        { "productName": "Laptop 14", "price": 2366, "rating": 4.2, "discount": 55, "availability": "yes" },
        { "productName": "Laptop 15", "price": 2376, "rating": 4.3, "discount": 60, "availability": "yes" },
        { "productName": "Laptop 16", "price": 2386, "rating": 4.4, "discount": 65, "availability": "yes" },
        { "productName": "Laptop 17", "price": 2396, "rating": 4.5, "discount": 70, "availability": "yes" },
        { "productName": "Laptop 18", "price": 2406, "rating": 4.6, "discount": 75, "availability": "yes" },
        { "productName": "Laptop 19", "price": 2416, "rating": 4.7, "discount": 80, "availability": "yes" },
        { "productName": "Laptop 20", "price": 2426, "rating": 4.8, "discount": 85, "availability": "yes" }
      ]
    } 
}

export const AMZ = product.AMZ;
export const categories = Object.keys(product.AMZ)